/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapp4;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javaapp4.homepage1;
import javaapp4.horror;

import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.SwingConstants;

/**
 *
 * @author MALKIT SINGH
 */
public class categories extends javax.swing.JFrame {

    /**
     * Creates new form categories
     */
    public categories() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\Gemini_Generated_Image__1_-removebg-preview.png")); // NOI18N

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\arrow-back (1).png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(132, 132, 132)))
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(754, 754, 754))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapp4/action.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel7.setText("ACTION");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(68, 68, 68))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\romance1.jpg")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel9.setText("Romance");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(7, 7, 7)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(68, 68, 68))
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\horror.jpg")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel11.setText("HORROR");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14))))
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\fantasy1.jpg")); // NOI18N

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel13.setText("Fantasy");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 970, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        homepage1 h1=new homepage1();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
                                    
        JFrame actionFrame = new JFrame();
    action actionPanel = new action();
             
                    
    // Create a new black panel with a white label
    JPanel topPanel = new JPanel(new GridBagLayout());
    topPanel.setBackground(Color.BLACK);
    topPanel.setForeground(Color.WHITE);
    
    // Create a label "Horror" with fixed position
    JLabel actionLabel = new JLabel("Action", SwingConstants.CENTER);
    actionLabel.setFont(new Font("MV boli", Font.BOLD, 30));
    actionLabel.setForeground(Color.WHITE);
    
    // Add the label to the panel with fixed position
    GridBagConstraints gbcLabel = new GridBagConstraints();
    gbcLabel.gridx = 0;
    gbcLabel.gridy = 0;
    gbcLabel.weightx = 1.0; // Expand horizontally
    gbcLabel.anchor = GridBagConstraints.CENTER;
    topPanel.add(actionLabel, gbcLabel);
    
    // Add an image icon to the panel with space
    ImageIcon icon = new ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\arrow-back (1).png");
    JLabel iconLabel = new JLabel(icon);
    
    // Add padding around the icon
    GridBagConstraints gbcIcon = new GridBagConstraints();
    gbcIcon.gridx = 0;
    gbcIcon.gridy = 0;
    gbcIcon.anchor = GridBagConstraints.WEST; // Align to the left
    gbcIcon.insets = new Insets(0, 20, 0, 0); // Adjust the left padding (20) as needed
    topPanel.add(iconLabel, gbcIcon);

    // Add the black panel to the horrorFrame
    topPanel.setOpaque(true);
    actionFrame.getContentPane().add(topPanel, BorderLayout.NORTH);
    actionFrame.getContentPane().add(new romance1(), BorderLayout.CENTER);

    // Add the horror panel to a JScrollPane
    JScrollPane scrollPane = new JScrollPane(actionPanel);
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    scrollPane.setBackground(Color.WHITE);
 iconLabel.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Handle the mouse click event for the icon
          categories c=new categories();
          c.setVisible(true);
        actionFrame.dispose();
        }
    });
    // Add the scrollPane to the horrorFrame
    actionFrame.add(scrollPane);
    actionFrame.setBackground(Color.WHITE);

    // Set the horrorFrame properties and make it visible
    actionFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    actionFrame.setSize(900, 600);
     
    actionFrame.getContentPane().add(scrollPane);
    actionFrame.setVisible(true);
 
 actionFrame.setLocationRelativeTo(null);
    // Close the categories window
    this.dispose();



                     


    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
        // TODO add your handling code here:
                   JFrame romanceFrame = new JFrame();
    romance1 romancePanel = new romance1();
             
                    
    // Create a new black panel with a white label
    JPanel topPanel = new JPanel(new GridBagLayout());
    topPanel.setBackground(Color.BLACK);
    topPanel.setForeground(Color.WHITE);
    
    // Create a label "Horror" with fixed position
    JLabel romanceLabel = new JLabel("Romance", SwingConstants.CENTER);
    romanceLabel.setFont(new Font("MV boli", Font.BOLD, 30));
    romanceLabel.setForeground(Color.WHITE);
    
    // Add the label to the panel with fixed position
    GridBagConstraints gbcLabel = new GridBagConstraints();
    gbcLabel.gridx = 0;
    gbcLabel.gridy = 0;
    gbcLabel.weightx = 1.0; // Expand horizontally
    gbcLabel.anchor = GridBagConstraints.CENTER;
    topPanel.add(romanceLabel, gbcLabel);
    
    // Add an image icon to the panel with space
    ImageIcon icon = new ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\arrow-back (1).png");
    JLabel iconLabel = new JLabel(icon);
    
    // Add padding around the icon
    GridBagConstraints gbcIcon = new GridBagConstraints();
    gbcIcon.gridx = 0;
    gbcIcon.gridy = 0;
    gbcIcon.anchor = GridBagConstraints.WEST; // Align to the left
    gbcIcon.insets = new Insets(0, 20, 0, 0); // Adjust the left padding (20) as needed
    topPanel.add(iconLabel, gbcIcon);

    // Add the black panel to the horrorFrame
    topPanel.setOpaque(true);
    romanceFrame.getContentPane().add(topPanel, BorderLayout.NORTH);
    romanceFrame.getContentPane().add(new romance1(), BorderLayout.CENTER);

    // Add the horror panel to a JScrollPane
    JScrollPane scrollPane = new JScrollPane(romancePanel);
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    scrollPane.setBackground(Color.WHITE);
 iconLabel.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Handle the mouse click event for the icon
          categories c=new categories();
          c.setVisible(true);
        romanceFrame.dispose();
        }
    });
    // Add the scrollPane to the horrorFrame
    romanceFrame.add(scrollPane);
    romanceFrame.setBackground(Color.WHITE);

    // Set the horrorFrame properties and make it visible
    romanceFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    romanceFrame.setSize(900, 600);
     
    romanceFrame.getContentPane().add(scrollPane);
    romanceFrame.setVisible(true);
 
 romanceFrame.setLocationRelativeTo(null);
    // Close the categories window
    this.dispose();



                     
  
        
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
        // TODO add your handling code here:
                                     
    // TODO add your handling code here:
                                 
    // TODO add your handling code here:
    JFrame horrorFrame = new JFrame();
    horror horrorPanel = new horror();
             
                    
    // Create a new black panel with a white label
    JPanel topPanel = new JPanel(new GridBagLayout());
    topPanel.setBackground(Color.BLACK);
    topPanel.setForeground(Color.WHITE);
    
    // Create a label "Horror" with fixed position
    JLabel horrorLabel = new JLabel("Horror", SwingConstants.CENTER);
    horrorLabel.setFont(new Font("MV boli", Font.BOLD, 30));
    horrorLabel.setForeground(Color.WHITE);
    
    // Add the label to the panel with fixed position
    GridBagConstraints gbcLabel = new GridBagConstraints();
    gbcLabel.gridx = 0;
    gbcLabel.gridy = 0;
    gbcLabel.weightx = 1.0; // Expand horizontally
    gbcLabel.anchor = GridBagConstraints.CENTER;
    topPanel.add(horrorLabel, gbcLabel);
    
    // Add an image icon to the panel with space
    ImageIcon icon = new ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\arrow-back (1).png");
    JLabel iconLabel = new JLabel(icon);
    
    // Add padding around the icon
    GridBagConstraints gbcIcon = new GridBagConstraints();
    gbcIcon.gridx = 0;
    gbcIcon.gridy = 0;
    gbcIcon.anchor = GridBagConstraints.WEST; // Align to the left
    gbcIcon.insets = new Insets(0, 20, 0, 0); // Adjust the left padding (20) as needed
    topPanel.add(iconLabel, gbcIcon);

    // Add the black panel to the horrorFrame
    topPanel.setOpaque(true);
    horrorFrame.getContentPane().add(topPanel, BorderLayout.NORTH);
    horrorFrame.getContentPane().add(new horror(), BorderLayout.CENTER);

    // Add the horror panel to a JScrollPane
    JScrollPane scrollPane = new JScrollPane(horrorPanel);
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    scrollPane.setBackground(Color.WHITE);
 iconLabel.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Handle the mouse click event for the icon
          categories c=new categories();
          c.setVisible(true);
        horrorFrame.dispose();
        }
    });
    // Add the scrollPane to the horrorFrame
    horrorFrame.add(scrollPane);
    horrorFrame.setBackground(Color.WHITE);

    // Set the horrorFrame properties and make it visible
    horrorFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    horrorFrame.setSize(900, 600);
     
    horrorFrame.getContentPane().add(scrollPane);
    horrorFrame.setVisible(true);
 
 horrorFrame.setLocationRelativeTo(null);
    // Close the categories window
    this.dispose();






    }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
        // TODO add your handling code here:
         JFrame fantasyFrame = new JFrame();
   Fantasy fantasyPanel = new Fantasy();
             
                    
    // Create a new black panel with a white label
    JPanel topPanel = new JPanel(new GridBagLayout());
    topPanel.setBackground(Color.BLACK);
    topPanel.setForeground(Color.WHITE);
    
    // Create a label "Horror" with fixed position
    JLabel horrorLabel = new JLabel("Fantasy", SwingConstants.CENTER);
    horrorLabel.setFont(new Font("MV boli", Font.BOLD, 30));
    horrorLabel.setForeground(Color.WHITE);
    
    // Add the label to the panel with fixed position
    GridBagConstraints gbcLabel = new GridBagConstraints();
    gbcLabel.gridx = 0;
    gbcLabel.gridy = 0;
    gbcLabel.weightx = 1.0; // Expand horizontally
    gbcLabel.anchor = GridBagConstraints.CENTER;
    topPanel.add(horrorLabel, gbcLabel);
    
    // Add an image icon to the panel with space
    ImageIcon icon = new ImageIcon("C:\\Users\\MALKIT SINGH\\Desktop\\java app\\javaapp4\\src\\javaapp4\\arrow-back (1).png");
    JLabel iconLabel = new JLabel(icon);
    
    // Add padding around the icon
    GridBagConstraints gbcIcon = new GridBagConstraints();
    gbcIcon.gridx = 0;
    gbcIcon.gridy = 0;
    gbcIcon.anchor = GridBagConstraints.WEST; // Align to the left
    gbcIcon.insets = new Insets(0, 20, 0, 0); // Adjust the left padding (20) as needed
    topPanel.add(iconLabel, gbcIcon);

    // Add the black panel to the horrorFrame
    topPanel.setOpaque(true);
    fantasyFrame.getContentPane().add(topPanel, BorderLayout.NORTH);
    fantasyFrame.getContentPane().add(new Fantasy(), BorderLayout.CENTER);

    // Add the horror panel to a JScrollPane
    JScrollPane scrollPane = new JScrollPane(fantasyPanel);
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    scrollPane.setBackground(Color.WHITE);
 iconLabel.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Handle the mouse click event for the icon
          categories c=new categories();
          c.setVisible(true);
        fantasyFrame.dispose();
        }
    });
    // Add the scrollPane to the horrorFrame
    fantasyFrame.add(scrollPane);
    fantasyFrame.setBackground(Color.WHITE);

    // Set the horrorFrame properties and make it visible
    fantasyFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    fantasyFrame.setSize(900, 600);
     
    fantasyFrame.getContentPane().add(scrollPane);
    fantasyFrame.setVisible(true);
 
 fantasyFrame.setLocationRelativeTo(null);
    // Close the categories window
    this.dispose();


    }//GEN-LAST:event_jPanel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categories().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables

}